server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dpsystem?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.195.130
    port: 6379
    password: 390041210
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.195.130
    port: 5672
    virtual-host: /hmdp
    username: she
    password: 390041210
    listener:  
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 500ms
          max-attempts: 3
          multiplier: 1
    connection-timeout: 200ms
    template:
      retry:
        enabled: true
        initial-interval: 500ms
        multiplier: 1
        max-attempts: 3
    publisher-confirm-type: correlated
    publisher-returns: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug